import { useState, useEffect } from 'react';

const fmt = (n) => '$' + n.toLocaleString('en-US');

function StatusBanner({ status, currentBid, onRaise }) {
  if (status === 'winning') {
    return (
      <div className="status-banner win">
        <span className="icon">✓</span>
        <span className="sb-text">You&apos;re the <b>highest bidder</b>. Hold tight.</span>
      </div>
    );
  }
  if (status === 'outbid') {
    return (
      <div className="status-banner lose">
        <span className="icon">!</span>
        <span className="sb-text">You&apos;ve been <b>outbid</b> — current is {fmt(currentBid)}.</span>
        <button className="link-btn" style={{ marginLeft: 'auto', color: 'var(--lose)' }} onClick={onRaise}>Raise →</button>
      </div>
    );
  }
  return null;
}

function BidForm({ currentBid, minInc, onPlace, prefill, label }) {
  const minNext = currentBid + minInc;
  const [val, setVal] = useState(String(prefill || minNext));
  const [err, setErr] = useState('');

  useEffect(() => { setVal(String(prefill || minNext)); setErr(''); }, [prefill, currentBid]);

  const quick = [minInc, minInc * 2, minInc * 4];
  const setQuick = (add) => { setVal(String(currentBid + add)); setErr(''); };

  const submit = () => {
    const n = Math.round(Number(val));
    if (!val || isNaN(n)) { setErr('Enter a valid amount.'); return; }
    if (n < minNext) { setErr(`Bid must be at least ${fmt(minNext)} (current + ${fmt(minInc)} increment).`); return; }
    setErr('');
    onPlace(n);
  };

  return (
    <div className="bid-form">
      <div className="quickbids">
        {quick.map((q) => (
          <button key={q} className="qb" onClick={() => setQuick(q)}>+{fmt(q)}</button>
        ))}
      </div>
      <div className="bid-input-row">
        <div className={'bid-input' + (err ? ' err' : '')}>
          <span className="cur">$</span>
          <input
            inputMode="numeric"
            value={val}
            onChange={(e) => { setVal(e.target.value.replace(/[^0-9]/g, '')); setErr(''); }}
            onKeyDown={(e) => e.key === 'Enter' && submit()}
          />
        </div>
        <button className="bid-submit" onClick={submit}>{label || 'Place bid'}</button>
      </div>
      {err
        ? <div className="bid-error"><span>⚠</span> {err}</div>
        : <div className="bid-help">Minimum next bid {fmt(minNext)} · increment {fmt(minInc)}</div>}
    </div>
  );
}

function MyBid({ myBid, status, onEdit }) {
  return (
    <div className="mybid">
      <div className="row">
        <span className="k">Your bid</span>
        <button className="link-btn" onClick={onEdit}>Raise bid</button>
      </div>
      <div className="row" style={{ marginTop: 6 }}>
        <span className="amt num">{fmt(myBid)}</span>
        <span style={{ fontSize: 12, color: status === 'winning' ? 'var(--win)' : 'var(--lose)' }}>
          {status === 'winning' ? '● Leading' : '● Outbid'}
        </span>
      </div>
      <div className="max-note">You&apos;ll be notified instantly if someone bids higher.</div>
    </div>
  );
}

function Feed({ bids }) {
  return (
    <div className="feed">
      <div className="feed-head">
        <span className="t">Live activity</span>
        <span className="live"><span className="dot" /> Live · {bids.length} bids</span>
      </div>
      <div className="feed-list">
        {bids.map((b, i) => (
          <div key={b.id} className={'feed-item' + (b.you ? ' you' : '')}>
            <span className="av" style={{ background: b.you ? 'linear-gradient(135deg,var(--gold-bright),var(--gold))' : `hsl(${b.hue} 45% 62%)` }}>
              {b.you ? '★' : b.name.slice(0, 1)}
            </span>
            <div className="who">
              <div className="n">{b.you ? 'You' : b.name}{i === 0 && <span className="tag">High</span>}</div>
              <div className="tm">{b.time}</div>
            </div>
            <span className="amt num">{fmt(b.amount)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function BidRail({ auction }) {
  const { startingBid, currentBid, minInc, myBid, status, bids, placeBid, bump } = auction;
  const [editing, setEditing] = useState(false);
  const showForm = myBid === null || editing;

  const handlePlace = (n) => { placeBid(n); setEditing(false); };

  return (
    <aside className="bidrail">
      <div className="lot-head">
        <div className="lot-toprow">
          <span className="lot-kicker">Single edition · 1 of 1</span>
          <span className="watching"><span className="dot" /> 214 watching</span>
        </div>
        <h1 className="lot-title">Untitled (Drift No. 7)</h1>
        <div className="lot-artist">Generated by Oxide Atelier · printed on organic heavyweight cotton</div>
        <p className="lot-desc">
          A one-off wearable artwork — a latent-space bloom, screen-printed in seven passes.
          Includes a signed provenance token.
        </p>
        <div className="lot-meta">
          <div className="m"><span className="k">Size</span><span className="v">Medium</span></div>
          <div className="m"><span className="k">Edition</span><span className="v">1 / 1</span></div>
          <div className="m"><span className="k">Ships</span><span className="v">Worldwide</span></div>
        </div>
      </div>

      <div className="price-block">
        <div className="price-row price-start">
          <span className="label">Starting bid</span>
          <span className="amt num">{fmt(startingBid)}</span>
        </div>
        <div className="current">
          <div className="price-row"><span className="label">Current bid</span></div>
          <div className={'amt' + (bump ? ' bump' : '')} key={currentBid}>
            <span className="cur num">$</span>
            <span className="num">{currentBid.toLocaleString('en-US')}</span>
          </div>
          <div className="sub">{bids.length} bids · {fmt(currentBid - startingBid)} over start</div>
        </div>
      </div>

      <StatusBanner status={status} currentBid={currentBid} onRaise={() => setEditing(true)} />

      {!showForm && myBid !== null && (
        <MyBid myBid={myBid} status={status} onEdit={() => setEditing(true)} />
      )}

      {showForm && (
        <BidForm
          currentBid={currentBid}
          minInc={minInc}
          prefill={editing ? currentBid + minInc : null}
          label={myBid === null ? 'Place bid' : 'Raise bid'}
          onPlace={handlePlace}
        />
      )}

      <Feed bids={bids} />
    </aside>
  );
}
